language: go

go:
  - 1.14.2

arch:
  - amd64
#  - arm64

services:
  - docker

script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  #  - make test
  - make
  - docker build -t ${DOCKER_USERNAME}/lottery:1.0 .
  - docker tag ${DOCKER_USERNAME}/lottery:1.0 ${DOCKER_USERNAME}/lottery:latest
  - docker push ${DOCKER_USERNAME}/lottery:1.0
  - docker push ${DOCKER_USERNAME}/lottery:latest